### ISSUE TITLE
cycling through bullet points yields weird results

### ISSUE THREAD

**Issue by clydebaron2000** [thingnotok/obsidian-toggle-list#9]
state group:
```
- ||
- ? ||
- ! ||
- $ ||
```
expected:
`- hi`
`- ? hi`
`- ! hi`
`- $ hi`
`- hi`
result:
`- hi`
`- ? hi`
`- ! hi`
`- $ hi`
`- ? $ hi`

reason: pattern matching for prefix is taking the smallest match rather than the largest match for replacing.
ie:
`- $ hi` results in `- ? $ hi` because the smallest pattern of `- ||` was matched and replaced first before `- $ ||`

**Comment by thingnotok** [comment]
Hi, sorry for the late reply, not sure why I didn't get the notification mail of this repo.
The problem is actually due to the use of special characters in states. A new release with fix for it is published. 
Now you can use all of the characters including "., +, *, ?, ^, $, (, ), [, ], {, }, |, \".
